# Generated by Django 5.0 on 2026-01-06 06:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_identifier', models.CharField(help_text='사용자 식별자 (IP 또는 세션 키)', max_length=100)),
                ('title', models.CharField(default='새로운 대화', help_text='대화 제목', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='활성 세션 여부')),
            ],
            options={
                'verbose_name': '채팅 세션',
                'verbose_name_plural': '채팅 세션들',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField(help_text='사용자 질문')),
                ('ai_response', models.TextField(help_text='AI 답변')),
                ('source_type', models.CharField(choices=[('internal-rag', '내부 문서'), ('web-search', '웹 검색'), ('fallback', 'AI 지식'), ('error', '오류')], default='internal-rag', max_length=20)),
                ('response_time', models.FloatField(blank=True, help_text='응답 시간(초)', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession')),
            ],
            options={
                'verbose_name': '채팅 메시지',
                'verbose_name_plural': '채팅 메시지들',
                'ordering': ['timestamp'],
            },
        ),
    ]
