# Generated by Django 5.0 on 2026-01-07 08:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='사업계획서 제목', max_length=200)),
                ('business_name', models.CharField(help_text='사업명/회사명', max_length=200)),
                ('business_type', models.CharField(choices=[('tech', '기술창업'), ('service', '서비스업'), ('manufacturing', '제조업'), ('retail', '유통/소매'), ('food', '음식/외식'), ('education', '교육'), ('healthcare', '헬스케어'), ('finance', '핀테크'), ('other', '기타')], default='tech', max_length=20)),
                ('current_stage', models.CharField(choices=[('idea', '아이디어 단계'), ('planning', '계획 수립'), ('prototype', '프로토타입'), ('mvp', 'MVP 개발'), ('launch', '출시 준비'), ('operating', '운영 중')], default='idea', max_length=20)),
                ('executive_summary', models.TextField(blank=True, help_text='사업 개요')),
                ('business_model', models.TextField(blank=True, help_text='비즈니스 모델')),
                ('target_market', models.TextField(blank=True, help_text='목표 시장')),
                ('competitive_advantage', models.TextField(blank=True, help_text='경쟁 우위')),
                ('required_funding', models.DecimalField(blank=True, decimal_places=0, help_text='필요 자금(원)', max_digits=12, null=True)),
                ('expected_revenue_year1', models.DecimalField(blank=True, decimal_places=0, help_text='1년차 예상 매출', max_digits=12, null=True)),
                ('expected_revenue_year3', models.DecimalField(blank=True, decimal_places=0, help_text='3년차 예상 매출', max_digits=12, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_complete', models.BooleanField(default=False, help_text='작성 완료 여부')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사업계획서',
                'verbose_name_plural': '사업계획서들',
                'ordering': ['-updated_at'],
            },
        ),
    ]
