# Generated by Django 5.0 on 2026-01-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_businessplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessplan',
            name='business_idea',
            field=models.TextField(blank=True, help_text='사업 아이디어 설명'),
        ),
        migrations.AddField(
            model_name='businessplan',
            name='differentiation',
            field=models.TextField(blank=True, help_text='차별화 포인트'),
        ),
        migrations.AddField(
            model_name='businessplan',
            name='main_product',
            field=models.TextField(blank=True, help_text='주요 제품/서비스'),
        ),
        migrations.AddField(
            model_name='businessplan',
            name='revenue_plan',
            field=models.TextField(blank=True, help_text='수익 모델'),
        ),
        migrations.AddField(
            model_name='businessplan',
            name='target_customer',
            field=models.TextField(blank=True, help_text='타겟 고객'),
        ),
    ]
