# Generated by Django 5.2 on 2026-01-10 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_businessplan_business_idea_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='사업 ID')),
                ('biz_name', models.CharField(max_length=500, verbose_name='사업명')),
                ('event_type', models.CharField(choices=[('deadline', '마감일'), ('start', '시작일'), ('presentation', '발표일'), ('custom', '직접입력')], default='deadline', max_length=50, verbose_name='일정 유형')),
                ('event_date', models.DateField(verbose_name='일정 날짜')),
                ('title', models.CharField(max_length=500, verbose_name='일정 제목')),
                ('description', models.TextField(blank=True, null=True, verbose_name='상세 설명')),
                ('url', models.URLField(blank=True, null=True, verbose_name='공고 URL')),
                ('reminder_days', models.IntegerField(default=3, verbose_name='알림 (일 전)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '캘린더 일정',
                'verbose_name_plural': '캘린더 일정들',
                'db_table': 'calendar_events',
                'ordering': ['event_date', '-created_at'],
            },
        ),
    ]
